name = "voice-notes-backend"
main = "src/index.js"
compatibility_date = "2024-04-05"

# to Enable Cloudflare AI
[ai]
binding = "AI"

# Linking DB
[[d1_databases]]
binding = "DB"
database_name = "voice-notes-db"
database_id = "c5af58da-b0d3-455d-b590-c80babb9ffe1"